### ISSUE TITLE
Please don't use flags for languages

### ISSUE THREAD

**Issue by zedejose** [brenoalvs/monk#356]
I understand that using flags to represent languages is the general consensus in most multi-language plugins (like WPML, Polylang, qTranslate, and most others), but the concept is simply wrong. For example the spanish flag does **not** represent the Spanish language and will leave all other speakers of said language wondering if theirs is supported (the whole of Latin America, and so on and so on). This is probably true of all of the most spoken languages in the world.

I'm not going to go into to the whole debate (which is extensively presented at the [Flags Are Not Languages website](http://www.flagsarenotlanguages.com/blog/), in particular here: http://www.flagsarenotlanguages.com/blog/iconography-for-translations-best-practice-for-communicating-availability-of-translated-content/

Monk seems to be brand new to the multi-language plugin space, and I'm really keen for it to get started on the right foot.

Thanks.

**Comment by brenoalvs** [comment]
Hi @zedejose
Thank you for your valuable feedback.

To solve the language representation problem we choose to use locale as WordPress does. Currently Monk shows the flags of the languages/regions (locales) that user selected on plugin setup. But you can optionally hide it from language switcher, of course.

But this link was enlightening cause there are many contents published in a same language to serve multiple regions.

We definetly can hide the flags by default. But also keeping the option to show them, because as cited in the link you sent:

> If the content is specific to language and country, then individual flags are highly appropriate. But languages within countries should not be generalised: many countries such as Belgium, Canada, India and Switzerland have a mix of different primary languages.

What do you think about it?

**Comment by zedejose** [comment]
Completely agree, but I think you may be taking this a bit out of context:

> If the content is specific to language and country, then individual flags are highly appropriate.

(i.e. this is almost _never_ the case, and when it is, it is for the visitor to say, not the site's admin, maybe)

That said, it was not my purpose to demand radical changes to your plugin. Hiding the flags (by default? 😄) would be fine, or even (see above) let the admin choose which flag applies to which language...

Thanks for the plugin, anyway
